# Configuration for the database connection
[database]
    # The username used for connecting to the database
    user_name = "root"

    # The password used for connecting to the database
    user_password = "samplePassword"

    # The name of the database to connect to
    name = "savannah_tech"

    # The hostname or IP address of the database server
    host = "localhost"

    # The port number on which the database server is listening
    port = "3306"

# Configuration for GitHub API interaction
[github]
    # The base URL for the GitHub API
    api_endpoint = "https://api.github.com"

    # The GitHub user token for accessing private repositories
    # Uncomment the line below and add your token if you need access to a private repository
    # user_token = ""

    # The name of the GitHub repository to interact with
    repository_name = "material-design-icons"

# Configuration for data pulling options
[option]
    # The cron schedule expression for periodically pulling data
    pulling_cron_job_spec = "@every 01h00m00s"

    # The start date for pulling data (in ISO 8601 format)
    # Leave empty if you don't want to set a specific start date
    # eg value: 2023-09-14 12:11:00
    pulling_start_date = ""

    # The end date for pulling data (in ISO 8601 format)
    pulling_end_date = ""

    # Whether to reset the collection of data before pulling new data
    reset_collection = true

# Configuration for the web server
[server]
    # Indicates whether the web server should be started
    run_web_server = true

    # The hostname or IP address on which the web server will listen
    web_server_host = "localhost"

    # The port number on which the web server will listen
    web_server_port = "8089"
