services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - "database"
    networks:
      - "mynet"

  database:
    platform: "linux/x86_64"
    image: "mysql:latest"
    container_name: "go-savannah-db"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "savannah_tech"
      MYSQL_ROOT_PASSWORD: "Rcgct6YZneSgRtT"
    volumes:
      - "./database/go-savannah-tech-db-schema.sql:/docker-entrypoint-initdb.d/go-savannah-tech-db-schema.sql"
    networks:
      - "mynet"

networks:
  mynet:
    driver: "bridge"